<?php

namespace Database\Seeders;

use App\Http\Modules\Codesumis\gruposTerapeuticos\Models\gruposTerapeuticos;
use Illuminate\Http\Response;
use Illuminate\Database\Seeder;

class gruposTerapeuticosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        try {
            $terapeuticos = [
                ['nombre' => 'Oncologia'],
                ['nombre' => 'Esteroides'],
                ['nombre' => 'Trombocitopenia'],
                ['nombre' => 'Psoriasis'],
                ['nombre' => 'Relajantes Musculares'],
                ['nombre' => 'Fibrosis Pulmonar Idiopatica'],
                ['nombre' => 'Inmunosupresores'],
                ['nombre' => 'Asma'],
                ['nombre' => 'Artritis'],
                ['nombre' => 'Edema Macular'],
                ['nombre' => 'Rehidratantes'],
                ['nombre' => 'Dispositivos Medicos'],
                ['nombre' => 'Antianemicos'],
                ['nombre' => 'Hormonas'],
                ['nombre' => 'Suplementos'],
                ['nombre' => 'Toxicidad Por Hierro'],
                ['nombre' => 'Analgesicos'],
                ['nombre' => 'Dislipidemia'],
                ['nombre' => 'Alzheimer-Demencia'],
                ['nombre' => 'Antibioticos'],
                ['nombre' => 'Diabetes'],
                ['nombre' => 'Antiparkinsonianos'],
                ['nombre' => 'Antidepresivos'],
                ['nombre' => 'Antitromboticos'],
                ['nombre' => 'Terapia Cardiaca'],
                ['nombre' => 'Soluciones Para Perfusion'],
                ['nombre' => 'Anticonvulsivantes'],
                ['nombre' => 'Inhaladores'],
                ['nombre' => 'Lubricantes'],
                ['nombre' => 'Vitaminas'],
                ['nombre' => 'Antihipertensivos'],
                ['nombre' => 'Desordenes Adictivos'],
                ['nombre' => 'Insuficiencia Pancreatica'],
                ['nombre' => 'Antiespasmodicos'],
                ['nombre' => 'Antiacidos, Antiulcerosos Y Antiflatulentos'],
                ['nombre' => 'Antimicoticos'],
                ['nombre' => 'Vih'],
                ['nombre' => 'Antihistaminicos'],
                ['nombre' => 'Hiperpotasemia'],
                ['nombre' => 'Antidiarreicos'],
                ['nombre' => 'Antipsicoticos'],
                ['nombre' => 'Propulsivos'],
                ['nombre' => 'Disfuncion Erectil'],
                ['nombre' => 'Mucoliticos'],
                ['nombre' => 'Glaucoma'],
                ['nombre' => 'Antiinflamatorios'],
                ['nombre' => 'Antigotosos'],
                ['nombre' => 'Queratosis Actinica'],
                ['nombre' => 'Antivaricosos'],
                ['nombre' => 'Terapia Biliar'],
                ['nombre' => 'Midriaticos'],
                ['nombre' => 'Descongestionantes Y Antitusivo'],
                ['nombre' => 'Tiroideos Y Antitiroideos'],
                ['nombre' => 'Hemostaticos'],
                ['nombre' => 'Soluciones'],
                ['nombre' => 'Emolientes Y Protectores'],
                ['nombre' => 'Antiparasitarios'],
                ['nombre' => 'Ansioliticos'],
                ['nombre' => 'Hipnoticos Y Sedantes'],
                ['nombre' => 'Incontinencia Urinaria'],
                ['nombre' => 'Anestesicos'],
                ['nombre' => 'Hipomagnesemia'],
                ['nombre' => 'Osteoporosis'],
                ['nombre' => 'Anti-Acne'],
                ['nombre' => 'Enfermedades Raras'],
                ['nombre' => 'Psicoestimulantes Y Nootropicos'],
                ['nombre' => 'Despigmentantes'],
                ['nombre' => 'Queratoconjuntivitis'],
                ['nombre' => 'Hepatitis B'],
                ['nombre' => 'Inmunoglobulinas'],
                ['nombre' => 'Antiherpeticos'],
                ['nombre' => 'Terapia Hepatica'],
                ['nombre' => 'Antidotos'],
                ['nombre' => 'Virus Sincitial Respiratorio'],
                ['nombre' => 'Esclerosis Lateral Amiotrofica'],
                ['nombre' => 'Hipertrofia Prostatica Benigna'],
                ['nombre' => 'Antisepticos Y Desinfectantes'],
                ['nombre' => 'Antipruriginosos'],
                ['nombre' => 'Antimigrañosos'],
                ['nombre' => 'Antialergicos'],
                ['nombre' => 'Vasculares'],
                ['nombre' => 'Hiperprolactinemia'],
                ['nombre' => 'Oticos'],
                ['nombre' => 'Capilares'],
                ['nombre' => 'Antiacaros'],
                ['nombre' => 'Antiemeticos Y Antinauseantes'],
                ['nombre' => 'Antivertiginosos'],
                ['nombre' => 'Deficit De Atención'],
                ['nombre' => 'Tuberculosis'],
                ['nombre' => 'Antiobesidad'],
                ['nombre' => 'Hiperfosfatemia'],
                ['nombre' => 'Antimicobacteriales'],
                ['nombre' => 'Insuficiencia Renal Cronica'],
                ['nombre' => 'Neutropenia'],
                ['nombre' => 'Hepatitis C'],
                ['nombre' => 'Antihemofilicos'],
                ['nombre' => 'Antirretrovirales'],
                ['nombre' => 'Inmunomoduladores'],
                ['nombre' => 'Agentes antineoplasicos'],
                ['nombre' => 'Antiglaucomatosos'],
                ['nombre' => 'Antivirales'],
                ['nombre' => 'Antiagregantes plaquetarios'],
                ['nombre' => 'Hipolipemiantes'],
                ['nombre' => 'Antiosteoartriticos'],
                ['nombre' => 'Terapia endocrina'],
                ['nombre' => 'Vacunas'],
                ['nombre' => 'Reguladores de calcio'],
                ['nombre' => 'Resinas de intercambio'],
                ['nombre' => 'Enfermedad de fabry'],
                ['nombre' => 'Enfermedad de pompe'],
                ['nombre' => 'Premedicacion oncologica'],
                ['nombre' => 'Miastemias gravis'],
                ['nombre' => 'Antiosteoporoticos'],
                ['nombre' => 'Antiepilepticos'],
                ['nombre' => 'Antineovascularizacion'],
                ['nombre' => 'Antidiabeticos'],
                ['nombre' => 'Anticoagulantes'],
                ['nombre' => 'Antiprostaticos'],
                ['nombre' => 'Antiuricemicos'],
                ['nombre' => 'Anticaspas'],
                ['nombre' => 'Antifungicos topicos'],
                ['nombre' => 'Antifungicos vaginales'],
                ['nombre' => 'Antifungicos'],
                ['nombre' => 'Antileprosos'],
                ['nombre' => 'Agentes quelantes'],
                ['nombre' => 'Antimicoticos vaginales'],
                ['nombre' => 'Antialopecicos'],
                ['nombre' => 'Anticerumen'],
                ['nombre' => 'Antituberculosis'],
                ['nombre' => 'Agentes desintoxicantes '],
                ['nombre' => 'Antimicoticos topicos'],
                ['nombre' => 'Antimetabolitos'],
                ['nombre' => 'Antineuropaticos'],
                ['nombre' => 'Antiraquitismo'],
                ['nombre' => 'Corticoides oticos'],
                ['nombre' => 'Corticoides topicos'],
                ['nombre' => 'Corticoides'],
                ['nombre' => 'Farmacos para incontinencia urinaria'],
                ['nombre' => 'Limpiadores'],
                ['nombre' => 'Dermatitis atopica'],
                ['nombre' => 'Cicatrizantes'],
                ['nombre' => 'Coadyuvantes'],
                ['nombre' => 'Constipacion idiopatica'],
                ['nombre' => 'Deficiencia de aminoacidos'],
                ['nombre' => 'Defectos del ciclo de la urea'],
                ['nombre' => 'Corea de huntington'],
                ['nombre' => 'Enzimas proteoliticas'],
                ['nombre' => 'Esclerosis multiple'],
                ['nombre' => 'Mucopolisacaridosis IV'],
                ['nombre' => 'Inmunoestimulantes'],
                ['nombre' => 'Enfermedad de crohn'],
                ['nombre' => 'Paludismo'],
                ['nombre' => 'Preparados magistrales'],
                ['nombre' => 'Enfermedad de huntington'],
                ['nombre' => 'Otros trastornos neurologicos'],
                ['nombre' => 'Otros productos dermatologicos'],
                ['nombre' => 'Otros productos ginecologicos'],
                ['nombre' => 'Otros'],
                ['nombre' => 'Antibioticos topicos'],
                ['nombre' => 'Antibioticos oftalmicos'],
                ['nombre' => 'Antibioticos oticos'],
                ['nombre' => 'Antibioticos vaginales'],
                ['nombre' => 'Antihipertensivos pulmonares']
            ];
            foreach ($terapeuticos as $terapeutico) {
                gruposTerapeuticos::updateOrCreate([
                    'nombre' => $terapeutico['nombre'],
                ], [
                    'nombre' => $terapeutico['nombre'],
                ]);
            }
        } catch (\Throwable $th) {
            return response()->json([
                'mensaje' => 'Error al ejecutar el seeder de grupos Terapeuticos'
            ], Response::HTTP_BAD_REQUEST);
        }
    }
}
