<?php

namespace Database\Seeders;

use App\Http\Modules\Paises\Models\Pais;
use Illuminate\Database\Seeder;
use Illuminate\Http\Response;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        try {
            $paises = [
                ['codigo_dane' => '013', 'nombre' => 'AFGANISTAN'],
                ['codigo_dane' => '017', 'nombre' => 'ALBANIA'],
                ['codigo_dane' => '023', 'nombre' => 'ALEMANIA'],
                ['codigo_dane' => '026', 'nombre' => 'ARMENIA'],
                ['codigo_dane' => '027', 'nombre' => 'ARUBA'],
                ['codigo_dane' => '029', 'nombre' => 'BOSNIA-HERZEGOVINA'],
                ['codigo_dane' => '031', 'nombre' => 'BURKINA FASSO'],
                ['codigo_dane' => '037', 'nombre' => 'ANDORRA'],
                ['codigo_dane' => '040', 'nombre' => 'ANGOLA'],
                ['codigo_dane' => '041', 'nombre' => 'ANGUILLA'],
                ['codigo_dane' => '043', 'nombre' => 'ANTIGUA Y BARBUDA'],
                ['codigo_dane' => '047', 'nombre' => 'ANTILLAS HOLANDESAS'],
                ['codigo_dane' => '053', 'nombre' => 'ARABIA SAUDITA'],
                ['codigo_dane' => '059', 'nombre' => 'ARGELIA'],
                ['codigo_dane' => '063', 'nombre' => 'ARGENTINA'],
                ['codigo_dane' => '069', 'nombre' => 'AUSTRALIA'],
                ['codigo_dane' => '072', 'nombre' => 'AUSTRIA'],
                ['codigo_dane' => '074', 'nombre' => 'AZERBAIJAN'],
                ['codigo_dane' => '077', 'nombre' => 'BAHAMAS'],
                ['codigo_dane' => '080', 'nombre' => 'BAHREIN'],
                ['codigo_dane' => '081', 'nombre' => 'BANGLADESH'],
                ['codigo_dane' => '083', 'nombre' => 'BARBADOS'],
                ['codigo_dane' => '087', 'nombre' => 'BELGICA'],
                ['codigo_dane' => '088', 'nombre' => 'BELICE'],
                ['codigo_dane' => '090', 'nombre' => 'BERMUDAS'],
                ['codigo_dane' => '091', 'nombre' => 'BELARUS'],
                ['codigo_dane' => '093', 'nombre' => 'BIRMANIA (MYANMAR)'],
                ['codigo_dane' => '097', 'nombre' => 'BOLIVIA'],
                ['codigo_dane' => '101', 'nombre' => 'BOTSWANA'],
                ['codigo_dane' => '105', 'nombre' => 'BRASIL'],
                ['codigo_dane' => '108', 'nombre' => 'BRUNEI DARUSSALAM'],
                ['codigo_dane' => '111', 'nombre' => 'BULGARIA'],
                ['codigo_dane' => '115', 'nombre' => 'BURUNDI'],
                ['codigo_dane' => '119', 'nombre' => 'BUTAN'],
                ['codigo_dane' => '127', 'nombre' => 'CABO VERDE'],
                ['codigo_dane' => '137', 'nombre' => 'CAIMAN, ISLAS'],
                ['codigo_dane' => '141', 'nombre' => 'CAMBOYA (KAMPUCHEA)'],
                ['codigo_dane' => '145', 'nombre' => 'CAMERUN, REPUBLICA UNIDA DEL'],
                ['codigo_dane' => '149', 'nombre' => 'CANADA'],
                ['codigo_dane' => '159', 'nombre' => 'SANTA SEDE'],
                ['codigo_dane' => '165', 'nombre' => 'COCOS (KEELING), ISLAS'],
                ['codigo_dane' => '169', 'nombre' => 'COLOMBIA'],
                ['codigo_dane' => '173', 'nombre' => 'COMORAS'],
                ['codigo_dane' => '177', 'nombre' => 'CONGO'],
                ['codigo_dane' => '183', 'nombre' => 'COOK, ISLAS'],
                ['codigo_dane' => '187', 'nombre' => 'COREA (NORTE), REPUBLICA POPULAR DEMOCRATICA DE'],
                ['codigo_dane' => '190', 'nombre' => 'COREA (SUR), REPUBLICA DE'],
                ['codigo_dane' => '193', 'nombre' => 'COSTA DE MARFIL'],
                ['codigo_dane' => '196', 'nombre' => 'COSTA RICA'],
                ['codigo_dane' => '198', 'nombre' => 'CROACIA'],
                ['codigo_dane' => '199', 'nombre' => 'CUBA'],
                ['codigo_dane' => '203', 'nombre' => 'CHAD'],
                ['codigo_dane' => '211', 'nombre' => 'CHILE'],
                ['codigo_dane' => '215', 'nombre' => 'CHINA'],
                ['codigo_dane' => '218', 'nombre' => 'TAIWAN (FORMOSA)'],
                ['codigo_dane' => '221', 'nombre' => 'CHIPRE'],
                ['codigo_dane' => '229', 'nombre' => 'BENIN'],
                ['codigo_dane' => '232', 'nombre' => 'DINAMARCA'],
                ['codigo_dane' => '235', 'nombre' => 'DOMINICA'],
                ['codigo_dane' => '239', 'nombre' => 'ECUADOR'],
                ['codigo_dane' => '240', 'nombre' => 'EGIPTO'],
                ['codigo_dane' => '242', 'nombre' => 'EL SALVADOR'],
                ['codigo_dane' => '243', 'nombre' => 'ERITREA'],
                ['codigo_dane' => '244', 'nombre' => 'EMIRATOS ARABES UNIDOS'],
                ['codigo_dane' => '245', 'nombre' => 'ESPAÑA'],
                ['codigo_dane' => '246', 'nombre' => 'ESLOVAQUIA'],
                ['codigo_dane' => '247', 'nombre' => 'ESLOVENIA'],
                ['codigo_dane' => '249', 'nombre' => 'ESTADOS UNIDOS'],
                ['codigo_dane' => '251', 'nombre' => 'ESTONIA'],
                ['codigo_dane' => '253', 'nombre' => 'ETIOPIA'],
                ['codigo_dane' => '259', 'nombre' => 'FEROE, ISLAS'],
                ['codigo_dane' => '267', 'nombre' => 'FILIPINAS'],
                ['codigo_dane' => '271', 'nombre' => 'FINLANDIA'],
                ['codigo_dane' => '275', 'nombre' => 'FRANCIA'],
                ['codigo_dane' => '281', 'nombre' => 'GABON'],
                ['codigo_dane' => '285', 'nombre' => 'GAMBIA'],
                ['codigo_dane' => '289', 'nombre' => 'GHANA'],
                ['codigo_dane' => '293', 'nombre' => 'GIBRALTAR'],
                ['codigo_dane' => '297', 'nombre' => 'GRANADA'],
                ['codigo_dane' => '301', 'nombre' => 'GRECIA'],
                ['codigo_dane' => '305', 'nombre' => 'GROENLANDIA'],
                ['codigo_dane' => '309', 'nombre' => 'GUADALUPE'],
                ['codigo_dane' => '313', 'nombre' => 'GUAM'],
                ['codigo_dane' => '317', 'nombre' => 'GUATEMALA'],
                ['codigo_dane' => '325', 'nombre' => 'GUAYANA FRANCESA'],
                ['codigo_dane' => '329', 'nombre' => 'GUINEA'],
                ['codigo_dane' => '331', 'nombre' => 'GUINEA ECUATORIAL'],
                ['codigo_dane' => '334', 'nombre' => 'GUINEA-BISSAU'],
                ['codigo_dane' => '337', 'nombre' => 'GUYANA'],
                ['codigo_dane' => '341', 'nombre' => 'HAITI'],
                ['codigo_dane' => '345', 'nombre' => 'HONDURAS'],
                ['codigo_dane' => '351', 'nombre' => 'HONG KONG'],
                ['codigo_dane' => '355', 'nombre' => 'HUNGRIA'],
                ['codigo_dane' => '361', 'nombre' => 'INDIA'],
                ['codigo_dane' => '365', 'nombre' => 'INDONESIA'],
                ['codigo_dane' => '369', 'nombre' => 'IRAK'],
                ['codigo_dane' => '372', 'nombre' => 'IRAN, REPUBLICA ISLAMICA DEL'],
                ['codigo_dane' => '375', 'nombre' => 'IRLANDA (EIRE)'],
                ['codigo_dane' => '379', 'nombre' => 'ISLANDIA'],
                ['codigo_dane' => '383', 'nombre' => 'ISRAEL'],
                ['codigo_dane' => '386', 'nombre' => 'ITALIA'],
                ['codigo_dane' => '391', 'nombre' => 'JAMAICA'],
                ['codigo_dane' => '399', 'nombre' => 'JAPON'],
                ['codigo_dane' => '403', 'nombre' => 'JORDANIA'],
                ['codigo_dane' => '406', 'nombre' => 'KAZAJSTAN'],
                ['codigo_dane' => '410', 'nombre' => 'KENIA'],
                ['codigo_dane' => '411', 'nombre' => 'KIRIBATI'],
                ['codigo_dane' => '412', 'nombre' => 'KIRGUIZISTAN'],
                ['codigo_dane' => '413', 'nombre' => 'KUWAIT'],
                ['codigo_dane' => '420', 'nombre' => 'LAOS, REPUBLICA POPULAR DEMOCRATICA DE'],
                ['codigo_dane' => '426', 'nombre' => 'LESOTHO'],
                ['codigo_dane' => '429', 'nombre' => 'LETONIA'],
                ['codigo_dane' => '431', 'nombre' => 'LIBANO'],
                ['codigo_dane' => '434', 'nombre' => 'LIBERIA'],
                ['codigo_dane' => '438', 'nombre' => 'LIBIA (INCLUYE FEZZAN)'],
                ['codigo_dane' => '440', 'nombre' => 'LIECHTENSTEIN'],
                ['codigo_dane' => '443', 'nombre' => 'LITUANIA'],
                ['codigo_dane' => '445', 'nombre' => 'LUXEMBURGO'],
                ['codigo_dane' => '447', 'nombre' => 'MACAO'],
                ['codigo_dane' => '448', 'nombre' => 'MACEDONIA'],
                ['codigo_dane' => '450', 'nombre' => 'MADAGASCAR'],
                ['codigo_dane' => '455', 'nombre' => 'MALAYSIA'],
                ['codigo_dane' => '458', 'nombre' => 'MALAWI'],
                ['codigo_dane' => '461', 'nombre' => 'MALDIVAS'],
                ['codigo_dane' => '464', 'nombre' => 'MALI'],
                ['codigo_dane' => '467', 'nombre' => 'MALTA'],
                ['codigo_dane' => '469', 'nombre' => 'MARIANAS DEL NORTE, ISLAS'],
                ['codigo_dane' => '472', 'nombre' => 'MARSHALL, ISLAS'],
                ['codigo_dane' => '474', 'nombre' => 'MARRUECOS'],
                ['codigo_dane' => '477', 'nombre' => 'MARTINICA'],
                ['codigo_dane' => '485', 'nombre' => 'MAURICIO'],
                ['codigo_dane' => '488', 'nombre' => 'MAURITANIA'],
                ['codigo_dane' => '493', 'nombre' => 'MEXICO'],
                ['codigo_dane' => '494', 'nombre' => 'MICRONESIA, ESTADOS FEDERADOS DE'],
                ['codigo_dane' => '496', 'nombre' => 'MOLDAVIA'],
                ['codigo_dane' => '497', 'nombre' => 'MONGOLIA'],
                ['codigo_dane' => '498', 'nombre' => 'MONACO'],
                ['codigo_dane' => '501', 'nombre' => 'MONSERRAT, ISLA'],
                ['codigo_dane' => '505', 'nombre' => 'MOZAMBIQUE'],
                ['codigo_dane' => '507', 'nombre' => 'NAMIBIA'],
                ['codigo_dane' => '508', 'nombre' => 'NAURU'],
                ['codigo_dane' => '511', 'nombre' => 'NAVIDAD (CHRISTMAS), ISLAS'],
                ['codigo_dane' => '517', 'nombre' => 'NEPAL'],
                ['codigo_dane' => '521', 'nombre' => 'NICARAGUA'],
                ['codigo_dane' => '525', 'nombre' => 'NIGER'],
                ['codigo_dane' => '528', 'nombre' => 'NIGERIA'],
                ['codigo_dane' => '531', 'nombre' => 'NIUE, ISLA'],
                ['codigo_dane' => '535', 'nombre' => 'NORFOLK, ISLA'],
                ['codigo_dane' => '538', 'nombre' => 'NORUEGA'],
                ['codigo_dane' => '542', 'nombre' => 'NUEVA CALEDONIA'],
                ['codigo_dane' => '545', 'nombre' => 'PAPUASIA NUEVA GUINEA'],
                ['codigo_dane' => '548', 'nombre' => 'NUEVA ZELANDIA'],
                ['codigo_dane' => '551', 'nombre' => 'VANUATU'],
                ['codigo_dane' => '556', 'nombre' => 'OMAN'],
                ['codigo_dane' => '566', 'nombre' => 'PACIFICO, ISLAS (USA)'],
                ['codigo_dane' => '576', 'nombre' => 'PAKISTAN'],
                ['codigo_dane' => '578', 'nombre' => 'PALAU, ISLAS'],
                ['codigo_dane' => '580', 'nombre' => 'PANAMA'],
                ['codigo_dane' => '586', 'nombre' => 'PARAGUAY'],
                ['codigo_dane' => '589', 'nombre' => 'PERU'],
                ['codigo_dane' => '593', 'nombre' => 'PITCAIRN, ISLA'],
                ['codigo_dane' => '599', 'nombre' => 'POLINESIA FRANCESA'],
                ['codigo_dane' => '603', 'nombre' => 'POLONIA'],
                ['codigo_dane' => '607', 'nombre' => 'PORTUGAL'],
                ['codigo_dane' => '611', 'nombre' => 'PUERTO RICO'],
                ['codigo_dane' => '618', 'nombre' => 'QATAR'],
                ['codigo_dane' => '628', 'nombre' => 'REINO UNIDO'],
                ['codigo_dane' => '640', 'nombre' => 'REPUBLICA CENTROAFRICANA'],
                ['codigo_dane' => '644', 'nombre' => 'REPUBLICA CHECA'],
                ['codigo_dane' => '647', 'nombre' => 'REPUBLICA DOMINICANA'],
                ['codigo_dane' => '660', 'nombre' => 'REUNION'],
                ['codigo_dane' => '665', 'nombre' => 'ZIMBABWE'],
                ['codigo_dane' => '670', 'nombre' => 'RUMANIA'],
                ['codigo_dane' => '675', 'nombre' => 'RUANDA'],
                ['codigo_dane' => '676', 'nombre' => 'RUSIA'],
                ['codigo_dane' => '677', 'nombre' => 'SALOMON, ISLAS'],
                ['codigo_dane' => '685', 'nombre' => 'SAHARA OCCIDENTAL'],
                ['codigo_dane' => '687', 'nombre' => 'SAMOA'],
                ['codigo_dane' => '690', 'nombre' => 'SAMOA NORTEAMERICANA'],
                ['codigo_dane' => '695', 'nombre' => 'SAN CRISTOBAL Y NIEVES'],
                ['codigo_dane' => '697', 'nombre' => 'SAN MARINO'],
                ['codigo_dane' => '700', 'nombre' => 'SAN PEDRO Y MIGUELON'],
                ['codigo_dane' => '705', 'nombre' => 'SAN VICENTE Y LAS GRANADINAS'],
                ['codigo_dane' => '710', 'nombre' => 'SANTA ELENA'],
                ['codigo_dane' => '715', 'nombre' => 'SANTA LUCIA'],
                ['codigo_dane' => '720', 'nombre' => 'SANTO TOME Y PRINCIPE'],
                ['codigo_dane' => '728', 'nombre' => 'SENEGAL'],
                ['codigo_dane' => '731', 'nombre' => 'SEYCHELLES'],
                ['codigo_dane' => '735', 'nombre' => 'SIERRA LEONA'],
                ['codigo_dane' => '741', 'nombre' => 'SINGAPUR'],
                ['codigo_dane' => '744', 'nombre' => 'SIRIA, REPUBLICA ARABE DE'],
                ['codigo_dane' => '748', 'nombre' => 'SOMALIA'],
                ['codigo_dane' => '750', 'nombre' => 'SRI LANKA'],
                ['codigo_dane' => '756', 'nombre' => 'SUDAFRICA, REPUBLICA DE'],
                ['codigo_dane' => '759', 'nombre' => 'SUDAN'],
                ['codigo_dane' => '764', 'nombre' => 'SUECIA'],
                ['codigo_dane' => '767', 'nombre' => 'SUIZA'],
                ['codigo_dane' => '770', 'nombre' => 'SURINAM'],
                ['codigo_dane' => '773', 'nombre' => 'SWAZILANDIA'],
                ['codigo_dane' => '774', 'nombre' => 'TADJIKISTAN'],
                ['codigo_dane' => '776', 'nombre' => 'TAILANDIA'],
                ['codigo_dane' => '780', 'nombre' => 'TANZANIA, REPUBLICA UNIDA DE'],
                ['codigo_dane' => '783', 'nombre' => 'DJIBOUTI'],
                ['codigo_dane' => '787', 'nombre' => 'TERRITORIO BRITANICO DEL OCEANO INDICO'],
                ['codigo_dane' => '788', 'nombre' => 'TIMOR DEL ESTE'],
                ['codigo_dane' => '800', 'nombre' => 'TOGO'],
                ['codigo_dane' => '805', 'nombre' => 'TOKELAU'],
                ['codigo_dane' => '810', 'nombre' => 'TONGA'],
                ['codigo_dane' => '815', 'nombre' => 'TRINIDAD Y TOBAGO'],
                ['codigo_dane' => '820', 'nombre' => 'TUNICIA'],
                ['codigo_dane' => '823', 'nombre' => 'TURCAS Y CAICOS, ISLAS'],
                ['codigo_dane' => '825', 'nombre' => 'TURKMENISTAN'],
                ['codigo_dane' => '827', 'nombre' => 'TURQUIA'],
                ['codigo_dane' => '828', 'nombre' => 'TUVALU'],
                ['codigo_dane' => '830', 'nombre' => 'UCRANIA'],
                ['codigo_dane' => '833', 'nombre' => 'UGANDA'],
                ['codigo_dane' => '845', 'nombre' => 'URUGUAY'],
                ['codigo_dane' => '847', 'nombre' => 'UZBEKISTAN'],
                ['codigo_dane' => '850', 'nombre' => 'VENEZUELA'],
                ['codigo_dane' => '855', 'nombre' => 'VIET NAM'],
                ['codigo_dane' => '863', 'nombre' => 'VIRGENES, ISLAS (BRITANICAS)'],
                ['codigo_dane' => '866', 'nombre' => 'VIRGENES, ISLAS (NORTEAMERICANAS)'],
                ['codigo_dane' => '870', 'nombre' => 'FIJI'],
                ['codigo_dane' => '875', 'nombre' => 'WALLIS Y FORTUNA, ISLAS'],
                ['codigo_dane' => '880', 'nombre' => 'YEMEN'],
                ['codigo_dane' => '885', 'nombre' => 'YUGOSLAVIA'],
                ['codigo_dane' => '888', 'nombre' => 'ZAIRE'],
                ['codigo_dane' => '890', 'nombre' => 'ZAMBIA'],
                ['codigo_dane' => '897', 'nombre' => 'ZONA NEUTRAL PALESTINA'],
            ];
            foreach ($paises as $pais) {
                Pais::updateOrCreate([
                    'nombre' => $pais['nombre']
                ],[
                    'nombre' => $pais['nombre'],
                    'codigo_dane' => $pais['codigo_dane'],
                ]);
            }

        } catch (\Throwable $th) {
            return response()->json([
                'mensaje' => 'Error al ejecutar el seeder de pais'
            ], Response::HTTP_BAD_REQUEST);
        }
    }
}
