<?php

namespace Database\Seeders;

use App\Http\Modules\Eventos\Sucesos\Models\Suceso;
use Illuminate\Database\Seeder;
use Illuminate\Http\Response;

class SucesoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {


        Suceso::create(['nombre' => 'Inoportunidad en entrega de medicamentos']);
        Suceso::create(['nombre' => 'Error en el diligenciamiento de ordenes medicas']);
        Suceso::create(['nombre' => 'Error de dispensacion de medicamentos']);
        Suceso::create(['nombre' => 'Error en la asignacion de citas']);
        Suceso::create(['nombre' => 'Retiro accidental de sondas, drenes o catéteres']);
        Suceso::create(['nombre' => 'Falta de oportunidad en la realización y reporte de ayudas dx']);
        Suceso::create(['nombre' => 'Inoportunidad en reporte de exámenes de laboratorio']);
        Suceso::create(['nombre' => 'Inoportunidad en toma de exámenes de laboratorio']);
        Suceso::create(['nombre' => 'Inoportunidad en el servicio de medicina transfusional']);
        Suceso::create(['nombre' => 'Inoportunidad en procesamiento de las muestras']);
        Suceso::create(['nombre' => 'Complicación derivada del procedimientos']);
        Suceso::create(['nombre' => 'Fallas técnicas del equipo']);
        Suceso::create(['nombre' => 'Repetición de placas']);
        Suceso::create(['nombre' => 'Toma de ayuda dx a paciente equivocado']);
        Suceso::create(['nombre' => 'Toma de examen de laboratorio a paciente equivocado']);
        Suceso::create(['nombre' => 'Entrega de resultado equivocado']);
        Suceso::create(['nombre' => 'Pérdida de muestras']);
        Suceso::create(['nombre' => 'Reacción alérgica al medio de contraste']);
        Suceso::create(['nombre' => 'Extravasación del medio de contraste']);
        Suceso::create(['nombre' => 'Lesiones en la piel']);
        Suceso::create(['nombre' => 'Suicidio de pacientes internados']);
        Suceso::create(['nombre' => 'Otra muerte secundaria a eventos adversos']);
        Suceso::create(['nombre' => 'Robo intrainstitucional de niños']);
        Suceso::create(['nombre' => 'Retención de cuerpos extraños en pacientes quirúrgicos']);
        Suceso::create(['nombre' => 'Mortalidad obstétrica']);
        Suceso::create(['nombre' => 'Mortalidad quirúrgica en cirugía electiva']);
        Suceso::create(['nombre' => 'Intervención en sitio equivocado']);
        Suceso::create(['nombre' => 'Entrega equivocada de un neonato']);
        Suceso::create(['nombre' => 'Cirugía en parte equivocada o en paciente equivocado']);
        Suceso::create(['nombre' => 'Otras secuelas permanentes y lesiones discapacitantes']);
        Suceso::create(['nombre' => 'Fractura de piezas dentarias']);
        Suceso::create(['nombre' => 'Complicaciones derivadas de procedimientos diagnósticos intervencionistas']);
        Suceso::create(['nombre' => 'Otro Evento adverso por retraso o cancelación de cirugía']);
        Suceso::create(['nombre' => 'Pacientes con diagnóstico de apendicitis que no son intervenidos después de 12 horas de realizado el diagnóstico']);
        Suceso::create(['nombre' => 'Luxación posquirúrgica en reemplazo de cadera']);
        Suceso::create(['nombre' => 'Dehiscencia de sutura']);
        Suceso::create(['nombre' => 'Pacientes con hipotensión severa en post quirúrgico']);
        Suceso::create(['nombre' => 'Eventos anestésicos']);
        Suceso::create(['nombre' => 'Neuropraxia de nervios periféricos asociada a posición de litotomía durante el parto o curetaje']);
        Suceso::create(['nombre' => 'Fallas en el proceso de gestión de muestras de patología']);
        Suceso::create(['nombre' => 'Quemaduras secundarias al uso de electro bisturí']);
        Suceso::create(['nombre' => 'Lesión vascular secundaria a procedimientos quirúrgicas']);
        Suceso::create(['nombre' => 'Complicaciones vasculares relacionadas con injerto']);
        Suceso::create(['nombre' => 'Rechazo del implante']);
        Suceso::create(['nombre' => 'Cefalea posterior a punción lumbar']);
        Suceso::create(['nombre' => 'Complicaciones y/o reacciones a dispositivos médicos']);
        Suceso::create(['nombre' => 'Uso inadecuado del Dispositivo Médico']);
        Suceso::create(['nombre' => 'No oportunidad o disponibilidad en suministro de Dispositivo Médico']);
        Suceso::create(['nombre' => 'Lesión de nervio en cirugía de piso pélvico']);
        Suceso::create(['nombre' => 'Mal funcionamiento por causas externas/Desconectado']);
        Suceso::create(['nombre' => 'Falla de calidad (Sistema, componente, accesorio, etiquetado)']);
        Suceso::create(['nombre' => 'Alergias por contacto']);
        Suceso::create(['nombre' => 'Obstrucción de la malla en cirugía de piso pélvico']);
        Suceso::create(['nombre' => 'Erosión de la malla material protésico), en cirugía de piso pélvico']);
        Suceso::create(['nombre' => 'Inadecuado Mantenimiento, Calibración, Inspección y/o Reparación']);
        Suceso::create(['nombre' => 'Quemaduras por lámpara de fototerapia y por electrocauterio']);
        Suceso::create(['nombre' => 'Trauma por caída de objetos pesados']);
        Suceso::create(['nombre' => 'Epistaxis secundaria a terapia respiratoria']);
        Suceso::create(['nombre' => 'Fuga de pacientes hospitalizados, incluyendo psiquiátricos']);
        Suceso::create(['nombre' => 'Extubación accidental']);
        Suceso::create(['nombre' => 'Administración de Medicamentos Y Hemoderivados']);
        Suceso::create(['nombre' => 'Complicaciones derivadas del cuidado de catéteres y sondas,']);
        Suceso::create(['nombre' => 'Caída de pacientes']);
        Suceso::create(['nombre' => 'Broncoaspiracion']);
        Suceso::create(['nombre' => 'Laceración']);
        Suceso::create(['nombre' => 'Ulcera por presión']);
        Suceso::create(['nombre' => 'Extubación']);
        Suceso::create(['nombre' => 'Toma de muestras de laboratorio por enfermería']);
        Suceso::create(['nombre' => 'Eventos adversos relacionados con el traslado interno de pacientes']);
        Suceso::create(['nombre' => 'Retiro no programado de catéteres venosos, sondas gástricas y vesicales, drenes quirúrgicos']);
        Suceso::create(['nombre' => 'Flebitis mecánica o química']);
        Suceso::create(['nombre' => 'Eventos relacionados con la dieta']);
        Suceso::create(['nombre' => 'Problemas relacionados con la manipulación o con la administración de medicamentos']);
        Suceso::create(['nombre' => 'Eventos adversos asociados a la vacunación']);
        Suceso::create(['nombre' => 'Reacciones medicamentosas']);
        Suceso::create(['nombre' => 'Problemas relacionados con la prescripción de medicamentos']);
        Suceso::create(['nombre' => 'Medicamento no disponible']);
        Suceso::create(['nombre' => 'No oportunidad en la entrega de medicamento']);
        Suceso::create(['nombre' => 'Medicamento de mala calidad']);
        Suceso::create(['nombre' => 'Falla terapéutica']);
        Suceso::create(['nombre' => 'Errores en entrega de medicamento']);
        Suceso::create(['nombre' => 'Problemas relacionadas con el uso de gas medicinal']);
        Suceso::create(['nombre' => 'Complicaciones relacionadas con la inmunosupresión']);
        Suceso::create(['nombre' => 'Incidentes y accidentes transfusionales y reacciones adversas a transfusiones y otras sustancias biológicas']);
        Suceso::create(['nombre' => 'Asfixia perinatal originado en la institución']);
        Suceso::create(['nombre' => 'Neumonía por Broncoaspiracion en niños']);
        Suceso::create(['nombre' => 'Neumotórax']);
        Suceso::create(['nombre' => 'Obstrucción del tubo endotraqueal']);
        Suceso::create(['nombre' => 'Paciente en estado crítico sin asistencia']);
        Suceso::create(['nombre' => 'Paciente obstétrica con convulsión intrahospitalaria']);
        Suceso::create(['nombre' => 'Shock hipovolémico evitable']);
        Suceso::create(['nombre' => 'Trastornos derivados de la mala nutrición']);
        Suceso::create(['nombre' => 'Trauma obstétrico grave secundarios a la atención']);
        Suceso::create(['nombre' => 'Gasa inadvertida que queda en el canal vaginal']);
        Suceso::create(['nombre' => 'Complicaciones derivadas del uso de tubo a tórax']);
        Suceso::create(['nombre' => 'Evento relacionados con atención inadecuada del código azul']);
        Suceso::create(['nombre' => 'Eventos atribuibles a fallas internas en la oportunidad o la continuidad de la evaluación']);
        Suceso::create(['nombre' => 'Evento derivado de procedimientos intervencionistas']);
        Suceso::create(['nombre' => 'Displasia broncopulmonar del recién nacido']);
        Suceso::create(['nombre' => 'Enfermedad tromboembólica venosa que ocurre en el hospital']);
        Suceso::create(['nombre' => 'Hemorragia intraventricular del prematuro grado III - IV']);
        Suceso::create(['nombre' => 'Hemorragia obstétrica por fallos en la atención']);
        Suceso::create(['nombre' => 'Mortalidad perinatal por fallos en la atención']);
        Suceso::create(['nombre' => 'Encefalopatía hipóxico isquémica Sarnat III']);
        Suceso::create(['nombre' => 'Mortalidad Perinatal y Neonatal ( 20 semanas de gestación a 30 días)']);
        Suceso::create(['nombre' => 'Morbilidad Obstétrica Hemorragia de origen obstétrico que requiera transfusión, laparotomía, histerectomía o']);
        Suceso::create(['nombre' => 'Ingreso a UCI']);
        Suceso::create(['nombre' => 'Lesiones perineales graves asociadas al parto (desgarro GIII - IV)']);
        Suceso::create(['nombre' => 'Farmacovigilancia']);
        Suceso::create(['nombre' => 'Relacionado con lesiones por presión']);
        Suceso::create(['nombre' => 'Relacionado con caída de paciente']);
        Suceso::create(['nombre' => 'Administración de hemoderivados']);
        Suceso::create(['nombre' => 'Relacionado con exámenes de laboratorio']);
        Suceso::create(['nombre' => 'Relacionado con ayudas diagnósticas ']);
        Suceso::create(['nombre' => 'Atención insegura del binomio madre-hijo ']);
        Suceso::create(['nombre' => 'Relacionados con procesos quirúrgicos']);
        Suceso::create(['nombre' => 'Infecciones asociadas al cuidado de la salud (IAAS)']);
        Suceso::create(['nombre' => 'Identificación del paciente']);
        Suceso::create(['nombre' => 'Error en la asignación de citas']);
        Suceso::create(['nombre' => 'Retiro accidental de sondas, drenes, catéter']);
        Suceso::create(['nombre' => 'Robo intrainstitucional de niños']);
        Suceso::create(['nombre' => 'Suicidio de pacientes internados']);
        Suceso::create(['nombre' => 'Fractura de piezas dentarias']);
        Suceso::create(['nombre' => 'Complicaciones derivadas de procesos diagnosticos intervencionistas']);
        Suceso::create(['nombre' => 'Fuga de paciente']);
        Suceso::create(['nombre' => 'Extubacion accidental']);
        Suceso::create(['nombre' => 'Broncoaspiracion']);
        Suceso::create(['nombre' => 'Relacionado con la dieta del paciente']);
        Suceso::create(['nombre' => 'Paciente en estado critico sin asistencia']);
        Suceso::create(['nombre' => 'Lesiones perineales graves asociadas al parto']);
        Suceso::create(['nombre' => 'Mortalidad perintal  o neonatal por fallos en la atención']);
        Suceso::create(['nombre' => 'Reingreso al servicio por la misma causa antes de 72 horas']);
        Suceso::create(['nombre' => 'Otros']);
        Suceso::create(['nombre' => 'Flebitis']);
        Suceso::create(['nombre' => 'Registros relacionados con historia clínica y consentimiento informado']);
        Suceso::create(['nombre' => 'Reingreso a UCE en menos de 48 horas y por la misma causa de egreso']);
        Suceso::create(['nombre' => 'Reingreso a UCI en menos de 48 horas  y por la misma causa de egreso']);
        Suceso::create(['nombre' => 'Reingreso a hospitalización en menos de 15 días  y por la misma causa de egreso']);
        Suceso::create(['nombre' => 'Tecnovigilancia']);
        Suceso::create(['nombre' => 'Otro (¿Cuál?)']);
        Suceso::create(['nombre' => 'Relacionado con sistemas y/o tecnologías']);
        Suceso::create(['nombre' => 'Relacionado con registros en la historia clínica']);
        Suceso::create(['nombre' => 'Relacionado con consentimientos informados']);
        Suceso::create(['nombre' => 'Relacionado con ambiente físico']);
        Suceso::create(['nombre' => 'Lesión intrahospitalaria']);
        Suceso::create(['nombre' => 'Traslado externo de pacientes']);
        Suceso::create(['nombre' => 'Lesiones por presión (Mencione el tipo y la categoría en la descripción)']);
        Suceso::create(['nombre' => 'Reingreso a urgencias por la misma causa antes de 72 horas']);
        Suceso::create(['nombre' => 'Reingreso a UCI por la misma causa antes de 72 horas']);
        Suceso::create(['nombre' => 'Reingreso a UCE por la misma causa antes de 72 horas']);
        Suceso::create(['nombre' => 'Muerte materna, perinatal  o neonatal']);
        Suceso::create(['nombre' => 'Inoportunidad en la atención']);
        Suceso::create(['nombre' => 'Retiro de dispositivos médicos (sondas, drenes, catéteres)']);
        Suceso::create(['nombre' => 'Asignación de citas']);
        Suceso::create(['nombre' => 'Traslado interno de pacientes']);
        Suceso::create(['nombre' => 'Reactivovigilancia']);
        Suceso::create(['nombre' => 'Omisión de orden medica']);
        Suceso::create(['nombre' => 'Extravasación']);
        Suceso::create(['nombre' => 'Infiltración']);
        Suceso::create(['nombre' => 'Biovigilancia']);
        Suceso::create(['nombre' => 'Relacionado con el comportamiento de paciente']);
        Suceso::create(['nombre' => 'Mortalidad']);
        Suceso::create(['nombre' => 'Trauma uretral']);
        Suceso::create(['nombre' => 'Ingreso hospitalario no pertinente']);
    }
}
