<?php

namespace Database\Seeders;

use App\Http\Modules\Eventos\TipoEventos\Models\TipoEvento;
use Illuminate\Database\Seeder;
use Illuminate\Http\Response;

class TipoSucesoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
             TipoEvento::create(['nombre' => 'Elección incorrecta del Medicamento', 'clasificacion_area_id' => 27]);
             TipoEvento::create(['nombre' => 'Elección o indicación incorrecta de la dosis', 'clasificacion_area_id' => 27]);
             TipoEvento::create(['nombre' => 'Información, instrucciones incorrectas al paciente por parte del médico tratante', 'clasificacion_area_id' => 27]);
             TipoEvento::create(['nombre' => 'Prescripción de un medicamento innecesario', 'clasificacion_area_id' => 27]);
             TipoEvento::create(['nombre' => 'Diagnóstico incorrecto', 'clasificacion_area_id' => 27]);
             TipoEvento::create(['nombre' => 'Duplicidad medicamentos', 'clasificacion_area_id' => 27]);
             TipoEvento::create(['nombre' => 'Ausencia del medicamento (faltantes) en la farmacia de la institución', 'clasificacion_area_id' => 28]);
             TipoEvento::create(['nombre' => 'Concentración (dosis) incorrecta', 'clasificacion_area_id' => 29]);
             TipoEvento::create(['nombre' => 'Forma farmacéutica incorrecta', 'clasificacion_area_id' => 29]);
             TipoEvento::create(['nombre' => 'Cantidad incorrecta', 'clasificacion_area_id' => 29]);
             TipoEvento::create(['nombre' => 'Omisión en la entrega del medicamento', 'clasificacion_area_id' => 29]);
             TipoEvento::create(['nombre' => 'Entrega de medicamento no autorizado', 'clasificacion_area_id' => 29]);
             TipoEvento::create(['nombre' => 'Medicamento no autorizado', 'clasificacion_area_id' => 30]);
             TipoEvento::create(['nombre' => 'Dosis incorrecta', 'clasificacion_area_id' => 30]);
             TipoEvento::create(['nombre' => 'Dosis omitidas', 'clasificacion_area_id' => 30]);
             TipoEvento::create(['nombre' => 'Vía incorrecta', 'clasificacion_area_id' => 30]);
             TipoEvento::create(['nombre' => 'Forma farmacéutica incorrecta', 'clasificacion_area_id' => 30]);
             TipoEvento::create(['nombre' => 'Técnica incorrecta', 'clasificacion_area_id' => 30]);
             TipoEvento::create(['nombre' => 'Tiempo de administración o infusión incorrecto', 'clasificacion_area_id' => 30]);
             TipoEvento::create(['nombre' => 'Monitorización incorrecta', 'clasificacion_area_id' => 30]);
             TipoEvento::create(['nombre' => 'Empaque de medicamento alterado', 'clasificacion_area_id' => 31]);
             TipoEvento::create(['nombre' => 'Identificación del medicamentos Incompleta o ausente', 'clasificacion_area_id' => 31]);
             TipoEvento::create(['nombre' => 'Medicamento con cambios en su presentación habitual (cambios de color, consistencia, material particulado)', 'clasificacion_area_id' => 31]);
             TipoEvento::create(['nombre' => 'Medicamento con fecha vencida', 'clasificacion_area_id' => 31]);
             TipoEvento::create(['nombre' => 'Sello seguridad del medicamento roto/ausente', 'clasificacion_area_id' => 31]);
             TipoEvento::create(['nombre' => 'Ausencia de prescripción de un medicamento necesario para el paciente', 'clasificacion_area_id' => 33]);
             TipoEvento::create(['nombre' => 'Presencia de prescripción de un medicamento innecesario para el paciente', 'clasificacion_area_id' => 33]);
             TipoEvento::create(['nombre' => 'Reacción adversa', 'clasificacion_area_id' => 34]);
             TipoEvento::create(['nombre' => 'Fallo terapéutico', 'clasificacion_area_id' => 32]);
             TipoEvento::create(['nombre' => 'Otras', 'clasificacion_area_id' => 28]);
             TipoEvento::create(['nombre' => 'Medicamento con fecha vencida', 'clasificacion_area_id' => 29]);
             TipoEvento::create(['nombre' => 'Hora incorrecta', 'clasificacion_area_id' => 30]);
             TipoEvento::create(['nombre' => 'Otras', 'clasificacion_area_id' => 31]);
             TipoEvento::create(['nombre' => 'Interacción medicamentosa ', 'clasificacion_area_id' => 33]);
             TipoEvento::create(['nombre' => 'Otras', 'clasificacion_area_id' => 34]);
             TipoEvento::create(['nombre' => 'Otras', 'clasificacion_area_id' => 32]);
             TipoEvento::create(['nombre' => 'Dispositivo médico incompleto', 'clasificacion_area_id' => 35]);
             TipoEvento::create(['nombre' => 'Dispositivo médico con empaque alterado', 'clasificacion_area_id' => 35]);
             TipoEvento::create(['nombre' => 'Dispositivo médico con etiqueta alterada', 'clasificacion_area_id' => 35]);
             TipoEvento::create(['nombre' => 'Dispositivo médico averiado y/o dañado', 'clasificacion_area_id' => 35]);
             TipoEvento::create(['nombre' => 'Dispositivo médico con presencia de material particulado cuerpo extraño', 'clasificacion_area_id' => 35]);
             TipoEvento::create(['nombre' => 'Dispositivo médico problemas de calidad', 'clasificacion_area_id' => 35]);
             TipoEvento::create(['nombre' => 'Dispositivo médico con fecha de vencida', 'clasificacion_area_id' => 35]);
             TipoEvento::create(['nombre' => 'Dispositivo médico con condiciones de preservación en el transporte alteradas', 'clasificacion_area_id' => 35]);
             TipoEvento::create(['nombre' => 'Uso anormal  ', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Respuesta fisiológica anormal o inesperada   ', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Falla en la alarma  ', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Uso de material biológico', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Calibración    ', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Hardware del computador del equipo ', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Contaminación durante la producción', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Contaminación post producción', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Diseño', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Desconeccion', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Componente eléctrico', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Circuito eléctrico', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Contacto eléctrico', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Interferencia electromagnética', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Fecha de expiración', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Falso negativo', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Falso positivo', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Resultado falso de la prueba', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Falla en el dispositivo implantable ', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Ambiente inapropiado', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Incompatibilidad', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Instrucciones para uso y etiquetado', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Escape/sellado', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Mantenimiento', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Fabricación', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Material', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Componentes mecánicos', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Condiciones no higiénicas', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'No relacionado con el dispositivo', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Otros', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Empaque', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Anatomía/fisiología del paciente', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Condición del paciente', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Fuente de energía', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Medidas de protección', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Aseguramiento de la calidad en la institución para la atención en salud', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Radiación', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Software', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Esterilización/desinfección/limpieza', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Condiciones de almacenamiento', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Alteración, falsificación y sabotaje', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Entrenamiento', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Transporte y entrega', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Sin identificar', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Capacidad de uso', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Error de uso', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Desgaste', 'clasificacion_area_id' => 36]);
             TipoEvento::create(['nombre' => 'Ausencia de prescripción de medicamentos necesarios', 'clasificacion_area_id' => 27]);
             TipoEvento::create(['nombre' => 'Cantidad incorrecta', 'clasificacion_area_id' => 27]);
             TipoEvento::create(['nombre' => 'Eleccion incorrecta de via de administración', 'clasificacion_area_id' => 27]);
             TipoEvento::create(['nombre' => 'Forma farmacéutica incorrecta', 'clasificacion_area_id' => 27]);
             TipoEvento::create(['nombre' => 'Información o instrucciones incorrectas al paciente', 'clasificacion_area_id' => 30]);
             TipoEvento::create(['nombre' => 'Monitorización incorrecta', 'clasificacion_area_id' => 33]);
             TipoEvento::create(['nombre' => 'Cantidad incorrecta', 'clasificacion_area_id' => 37]);
             TipoEvento::create(['nombre' => 'Eleccion incorrecta via administración', 'clasificacion_area_id' => 37]);
             TipoEvento::create(['nombre' => 'Eleccion incorrecta del medicamento', 'clasificacion_area_id' => 37]);
             TipoEvento::create(['nombre' => 'Dosis incorrecta', 'clasificacion_area_id' => 37]);
             TipoEvento::create(['nombre' => 'Ilegibilidad u omision en información', 'clasificacion_area_id' => 37]);
             TipoEvento::create(['nombre' => 'Forma farmaceutica incorrecta', 'clasificacion_area_id' => 37]);
             TipoEvento::create(['nombre' => 'Error de administración', 'clasificacion_area_id' => 38]);
             TipoEvento::create(['nombre' => 'Fallo Terapéutico asociado a Vacuna', 'clasificacion_area_id' => 38]);
             TipoEvento::create(['nombre' => 'Reaccion adversa a vacuna', 'clasificacion_area_id' => 38]);
             TipoEvento::create(['nombre' => 'Falta de adherencia terapéutica', 'clasificacion_area_id' => 33]);
             TipoEvento::create(['nombre' => 'Monitorización insuficiente del tratamiento', 'clasificacion_area_id' => 27]);
             TipoEvento::create(['nombre' => 'Paciente equivocado', 'clasificacion_area_id' => 27]);
             TipoEvento::create(['nombre' => 'Duración del tratamiento incorrecta', 'clasificacion_area_id' => 27]);
             TipoEvento::create(['nombre' => 'Medicamento contraindicado', 'clasificacion_area_id' => 27]);
             TipoEvento::create(['nombre' => 'Dispensación de un medicamento diferente al prescrito', 'clasificacion_area_id' => 29]);
             TipoEvento::create(['nombre' => 'Frecuencia incorrecta', 'clasificacion_area_id' => 30]);
             TipoEvento::create(['nombre' => 'Error de preparación/manipulación del medicamento', 'clasificacion_area_id' => 30]);
             TipoEvento::create(['nombre' => 'Paciente equivocado', 'clasificacion_area_id' => 30]);
             TipoEvento::create(['nombre' => 'Duración del tratamiento incorrecta', 'clasificacion_area_id' => 30]);
             TipoEvento::create(['nombre' => 'Automedicación', 'clasificacion_area_id' => 30]);
             TipoEvento::create(['nombre' => 'Administración de medicamento no prescrito', 'clasificacion_area_id' => 30]);
             TipoEvento::create(['nombre' => 'Paciente equivocado', 'clasificacion_area_id' => 37]);
             TipoEvento::create(['nombre' => 'Duración del tratamiento incorrecta', 'clasificacion_area_id' => 37]);
             TipoEvento::create(['nombre' => 'Transcripción de un medicamento diferente al prescrito', 'clasificacion_area_id' => 37]);
             TipoEvento::create(['nombre' => 'Medicamento de estrecho margen terapéutico', 'clasificacion_area_id' => 32]);
             TipoEvento::create(['nombre' => 'Resistencia parcial, total, natural o adquirida a la terapia', 'clasificacion_area_id' => 32]);
             TipoEvento::create(['nombre' => 'Asociado a tolerancia o taquifilaxia', 'clasificacion_area_id' => 32]);
             TipoEvento::create(['nombre' => 'Asociado a refractariedad', 'clasificacion_area_id' => 32]);
             TipoEvento::create(['nombre' => 'Problemas de calidad', 'clasificacion_area_id' => 32]);
             TipoEvento::create(['nombre' => 'Dosis, pauta y/o duración no adecuada', 'clasificacion_area_id' => 32]);
             TipoEvento::create(['nombre' => 'Problema de salud insuficientemente tratado', 'clasificacion_area_id' => 32]);
             TipoEvento::create(['nombre' => 'Conservación inadecuada', 'clasificacion_area_id' => 32]);
             TipoEvento::create(['nombre' => 'Error de dispensación', 'clasificacion_area_id' => 32]);
             TipoEvento::create(['nombre' => 'Error medicamento LASA', 'clasificacion_area_id' => 27]);
             TipoEvento::create(['nombre' => 'Error medicamento LASA', 'clasificacion_area_id' => 30]);
             TipoEvento::create(['nombre' => 'Error medicamento LASA', 'clasificacion_area_id' => 29]);
             TipoEvento::create(['nombre' => 'Error medicamento LASA', 'clasificacion_area_id' => 37]);
             TipoEvento::create(['nombre' => 'Fármaco ineficaz', 'clasificacion_area_id' => 34]);
             TipoEvento::create(['nombre' => 'Polifarmacia', 'clasificacion_area_id' => 33]);
             TipoEvento::create(['nombre' => 'Duplicidad', 'clasificacion_area_id' => 67]);
             TipoEvento::create(['nombre' => 'Interacción', 'clasificacion_area_id' => 67]);
             TipoEvento::create(['nombre' => 'Contraindicación', 'clasificacion_area_id' => 67]);
             TipoEvento::create(['nombre' => 'Dosis no adecuada', 'clasificacion_area_id' => 67]);
             TipoEvento::create(['nombre' => 'Duración no adecuada', 'clasificacion_area_id' => 67]);
             TipoEvento::create(['nombre' => 'Pauta no adecuada', 'clasificacion_area_id' => 67]);
             TipoEvento::create(['nombre' => 'Fármaco ineficaz', 'clasificacion_area_id' => 67]);
             TipoEvento::create(['nombre' => 'Probabilidad de efectos adversos', 'clasificacion_area_id' => 67]);
             TipoEvento::create(['nombre' => 'Falta de adherencia al tratamiento', 'clasificacion_area_id' => 67]);
             TipoEvento::create(['nombre' => 'Uso inadecuado de medicamento por parte del paciente', 'clasificacion_area_id' => 67]);
             TipoEvento::create(['nombre' => 'Automedicación', 'clasificacion_area_id' => 67]);
             TipoEvento::create(['nombre' => 'Prescripción de medicamento innecesario', 'clasificacion_area_id' => 67]);
             TipoEvento::create(['nombre' => 'Prescripción potencialmente inapropiada', 'clasificacion_area_id' => 67]);
             TipoEvento::create(['nombre' => 'Ausencia de prescripción de medicamento necesario', 'clasificacion_area_id' => 67]);
             TipoEvento::create(['nombre' => 'Error de prescripción', 'clasificacion_area_id' => 84]);
             TipoEvento::create(['nombre' => 'Error de admisnitración', 'clasificacion_area_id' => 84]);
             TipoEvento::create(['nombre' => 'Error de dispensación', 'clasificacion_area_id' => 84]);
             TipoEvento::create(['nombre' => 'Error de disponibilidad', 'clasificacion_area_id' => 84]);
             TipoEvento::create(['nombre' => 'Reacción adversa', 'clasificacion_area_id' => 84]);
             TipoEvento::create(['nombre' => 'Fallo terapéutico', 'clasificacion_area_id' => 84]);
             TipoEvento::create(['nombre' => 'Falta de adherencia terapéutica', 'clasificacion_area_id' => 84]);


    }
}
