<?php

namespace App\Enums\Homologos\Fomag;

enum FinalidadTranscripcionEnum: int
{
    /**
     * obtiene un valor particular del enum
     */
    public static function homologo(null|string $value): int
    {
        return match ($value) {
            "VALORACION INTEGRAL PARA LA PROMOCION Y MANTENIMIENTO" => 1,
            "DETECCION TEMPRANA DE ENFERMEDAD GENERAL" => 2,
            "DETECCION TEMPRANA DE ENFERMEDAD LABORAL" => 3,
            "PROTECCION ESPECIFICA" => 4,
            "DIAGNOSTICO" => 5,
            "TRATAMIENTO" => 6,
            "REHABILITACION" => 7,
            "PALIACION" => 8,
            "PLANIFICACION FAMILIAR Y ANTICONCEPCION" => 9,
            "PROMOCION Y APOYO A LA LACTANCIA MATERNA" => 10,
            "ATENCION BASICA DE ORIENTACION FAMILIAR" => 11,
            "ATENCION PARA EL CUIDADO PRECONCEPCIONAL" => 12,
            "ATENCION PARA EL CUIDADO PRENATAL" => 13,
            "INTERRUPCION VOLUNTARIA DEL EMBARAZO" => 14,
            "ATENCION DEL PARTO Y PUERPERIO" => 15,
            "ATENCION PARA EL CUIDADO DEL RECIEN NACIDO" => 16,
            "ATENCION PARA EL SEGUIMIENTO DEL RECIEN NACIDO" => 17,
            "PREPARACION PARA LA MATERNIDAD Y LA PATERNIDAD" => 18,
            "PROMOCION DE ACTIVIDAD FISICA" => 19,
            "PROMOCION DE LA CESACION DEL TABAQUISMO" => 20,
            "PREVENCION DEL CONSUMO DE SUSTANCIAS PSICOACTIVAS" => 21,
            "PROMOCION DE LA ALIMENTACION SALUDABLE" => 22,
            "PROMOCION PARA EL EJERCICIO DE LOS DERECHOS SEXUALES Y DERECHOS REPRODUCTIVOS" => 23,
            "PROMOCION PARA EL DESARROLLO DE HABILIDADES PARA LA VIDA" => 24,
            "PROMOCION PARA LA CONSTRUCCION DE ESTRATEGIAS DE AFRONTAMIENTO FRENTE A SUCESOS VITALES" => 25,
            "PROMOCION DE LA SANA CONVIVENCIA Y EL TEJIDO  SOCIAL" => 26,
            "PROMOCION DE UN AMBIENTE SEGURO Y DE CUIDADO Y PROTECCION DEL AMBIENTE" => 27,
            "PROMOCION DEL EMPODERAMIENTO PARA EL EJERCICIO DEL DERECHO A LA SALUD" => 28,
            "PROMOCION PARA LA ADOPCION DE PRACTICAS DE CRIANZA Y CUIDADO PARA LA SALUD" => 29,
            "PROMOCION DE LA CAPACIDAD DE LA AGENCIA Y CUIDADO DE LA SALUD" => 30,
            "DESARROLLO DE HABILIDADES COGNITIVAS" => 31,
            "INTERVENCION COLECTIVA" => 32,
            "MODIFICACION DE LA ESTETICA CORPORAL (FINES ESTETICOS)" => 33,
            "OTRA" => 34,
            default => 34
        };
    }
}
